# Generated by Django 4.2.3 on 2023-07-09 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 22, 41, 27, 797584, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 22, 41, 27, 798668, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 22, 41, 27, 799095, tzinfo=datetime.timezone.utc)),
        ),
    ]
