# Generated by Django 4.2.3 on 2023-10-14 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_creation_date_alter_bid_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 14, 12, 40, 12, 759527, tzinfo=datetime.timezone.utc)),
        ),
    ]
