# Generated by Django 4.2.3 on 2023-10-14 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_comment_creation_date_comment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dark_theme',
        ),
    ]
